"""Generate C++ test vectors for LaserGeo from VGCS compute_lrf_slant_geo.

Run from the repo root after changing either side:

    python apk/custom/test/gen_laser_vectors.py

It writes apk/custom/test/laser_geo_vectors.inc.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from vgcs.observe.geo_reference import compute_lrf_slant_geo  # noqa: E402

OUT = Path(__file__).with_name("laser_geo_vectors.inc")

# lat, lon, heading, roll, pitch, alt_msl (None = unknown), gimbal yaw, gimbal pitch, range, u, v, hfov, vfov (None = 16:9)
CASES = [
    (20.4459722, 72.8629682, 0.0, 0.0, 0.0, 120.0, 0.0, -30.0, 500.0, 0.5, 0.5, 83.4, None),
    (20.4459722, 72.8629682, 90.0, 0.0, 0.0, 120.0, 0.0, -30.0, 500.0, 0.5, 0.5, 83.4, None),
    (20.4459722, 72.8629682, 271.5, 2.0, -3.0, 350.5, 25.0, -12.5, 1180.0, 0.5, 0.5, 61.4, 47.9),
    (20.4459722, 72.8629682, 45.0, -4.0, 6.0, None, -60.0, -45.0, 250.0, 0.5, 0.5, 83.4, None),
    (34.4739, 74.0444, 180.0, 0.0, 0.0, 2500.0, 10.0, -90.0, 300.0, 0.5, 0.5, 83.4, None),
    (34.4739, 74.0444, 359.9, 1.0, 1.0, 2500.0, -170.0, -2.0, 950.0, 0.5, 0.5, 83.4, None),
    (-33.8688, 151.2093, 135.0, 0.0, 0.0, 50.0, 30.0, -20.0, 80.0, 0.75, 0.25, 83.4, 46.9),
    (-33.8688, 151.2093, 10.0, 0.0, 0.0, 50.0, 0.0, -20.0, 80.0, 0.0, 1.0, 100.0, 52.0),
    (51.5, -0.12, 200.0, 10.0, -10.0, 100.0, 90.0, 10.0, 1500.0, 0.5, 0.5, 14.7, 11.1),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -45.0, 100.0, 0.5, 0.5, 83.4, None),
    (20.0, 72.0, 30.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.4, 0.5, 0.5, 83.4, None),  # too short: refused
]


def num(v) -> str:
    return repr(float(v))


def main() -> int:
    lines = ["// Generated by gen_laser_vectors.py from vgcs/observe/geo_reference.py. Do not edit.", ""]
    for (lat, lon, hdg, roll, pitch, alt, gy, gp, rng, u, v, hfov, vfov) in CASES:
        r = compute_lrf_slant_geo(
            vehicle_lat=lat, vehicle_lon=lon, vehicle_heading_deg=hdg,
            vehicle_roll_deg=roll, vehicle_pitch_deg=pitch, vehicle_alt_msl_m=alt,
            gimbal_yaw_deg=gy, gimbal_pitch_deg=gp, slant_range_m=rng,
            video_x_norm=u, video_y_norm=v, gps_fix_type=3, gps_hdop=0.8,
            camera_hfov_deg=hfov, camera_vfov_deg=vfov,
        )
        geometric = r.target_lat is not None
        alt_arg = "std::nullopt" if alt is None else num(alt)
        vfov_arg = "std::nullopt" if vfov is None else num(vfov)
        exp_alt_has = "true" if r.target_alt_m is not None else "false"
        exp_alt = num(r.target_alt_m if r.target_alt_m is not None else 0.0)
        lines.append(
            "checkLaser(__LINE__, makeInput(" + ", ".join([num(lat), num(lon), num(hdg), num(roll), num(pitch), alt_arg,
                                          num(gy), num(gp), num(rng), num(u), num(v), num(hfov), vfov_arg]) + "), "
            + ("true" if geometric else "false") + ", "
            + ", ".join([num(r.target_lat or 0.0), num(r.target_lon or 0.0), exp_alt_has, exp_alt,
                         num(r.horizontal_range_m or 0.0), num(r.depression_deg or 0.0), num(r.bearing_deg or 0.0)])
            + ");"
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(CASES)} cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
