"""Make the APK's thermal colour modes from VGCS's own colour tables.

Run from the repo root after changing vgcs/video/thermal_palette.py or the
shader (apk/custom/res/shaders/thermal_palette.frag):

    python apk/make_thermal_palettes.py
    python apk/make_thermal_palettes.py path/to/qsb.exe

It writes:

- apk/custom/res/Images/thermal_palettes.png: one row of 256 colours per mode,
  in VGCS's menu order. Row 0 is the grey ramp of "as received".
- apk/custom/res/shaders/thermal_palette.frag.qsb: the shader, compiled by Qt's
  qsb for every graphics API Qt Quick uses (--qt6), so the APK build needs no
  shader tools.
- apk/custom/test/thermal_palette_vectors.inc: the ids, names and colours, for
  the link test and the screen preview.

Needs PySide6 (VGCS's module uses it) and Qt's qsb. The default qsb is the one
of the Qt 6.11.1 msvc2022_64 kit, the APK build's host kit.
"""

from __future__ import annotations

import struct
import subprocess
import sys
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from vgcs.video.thermal_palette import palette_ids, palette_label, swatch_colors  # noqa: E402

CUSTOM = REPO / "apk" / "custom"
TABLE = CUSTOM / "res" / "Images" / "thermal_palettes.png"
SHADER = CUSTOM / "res" / "shaders" / "thermal_palette.frag"
VECTORS = CUSTOM / "test" / "thermal_palette_vectors.inc"
DEFAULT_QSB = Path(r"C:\Qt\6.11.1\msvc2022_64\bin\qsb.exe")


def write_png(path: Path, rows: list[tuple[tuple[int, int, int], ...]]) -> None:
    """An 8-bit RGB PNG with no colour space chunks, so Qt loads the values as they are."""
    width, height = len(rows[0]), len(rows)
    raw = b"".join(b"\x00" + bytes(v for rgb in row for v in rgb) for row in rows)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(raw, 9))
                     + chunk(b"IEND", b""))


def c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_vectors(path: Path, ids: tuple[str, ...], rows: list[tuple[tuple[int, int, int], ...]]) -> None:
    out = [
        "// Generated by apk/make_thermal_palettes.py from vgcs/video/thermal_palette.py. Do not edit.",
        "// The thermal colour modes in VGCS's menu order: id, name, and the colour of each",
        '// grey level 0 to 255 ("as received" keeps the grey level).',
        "",
        f"static const int kThermalPaletteCount = {len(ids)};",
        "static const char *const kThermalPaletteIds[] = {" + ", ".join(c_string(i) for i in ids) + "};",
        "static const char *const kThermalPaletteNames[] = {"
        + ", ".join(c_string(palette_label(i)) for i in ids) + "};",
        f"static const unsigned char kThermalPaletteColours[{len(ids)}][256][3] = {{",
    ]
    for pid, row in zip(ids, rows):
        out.append(f"    // {pid}")
        out.append("    {")
        for start in range(0, 256, 8):
            out.append("        " + " ".join("{%d, %d, %d}," % rgb for rgb in row[start:start + 8]))
        out.append("    },")
    out.append("};")
    path.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")


def compile_shader(qsb: Path) -> Path:
    if not qsb.is_file():
        raise SystemExit(f"qsb not found: {qsb} (give its path as the first argument)")
    target = SHADER.with_name(SHADER.name + ".qsb")
    subprocess.run([str(qsb), "--qt6", "-o", str(target), str(SHADER)], check=True)
    return target


def main() -> None:
    qsb = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_QSB
    ids = palette_ids()
    rows = [swatch_colors(pid) for pid in ids]
    assert all(len(row) == 256 for row in rows)
    write_png(TABLE, rows)
    write_vectors(VECTORS, ids, rows)
    target = compile_shader(qsb)
    for path in (TABLE, target, VECTORS):
        print(f"wrote {path.relative_to(REPO)} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
